# base-image for debian buster on any machine using a template variable,
# see more about dockerfile templates here: https://www.balena.io/docs/learn/develop/dockerfile/#dockerfile-templates
# and about balena base images here: https://www.balena.io/docs/reference/base-images/base-images/
FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.8.6-buster-build

# Using -build image because psutil install requires gcc

RUN pip3 install smbus2 paho-mqtt psutil
COPY *.py /

ENTRYPOINT ["python3", "/pub.py"]