version: '2.1'
volumes:
  cam-data: {}
services:
  cam:
    restart: never
    build: ./cam
    privileged: true
    volumes:
      - 'cam-data:/data'
  uploader:
    restart: never
    build: ./uploader
    volumes:
      - 'cam-data:/data'
  web:
    build: ./web
    network_mode: "host"
    volumes:
      - 'cam-data:/var/www/html/static/data'
  sysmon:
    restart: never
    build: ./sysmon
    privileged: true
  heatercontrol:
    restart: always
    build: ./heatercontrol
    privileged: true
  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    labels:
      io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"