FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.8.6-buster-build

# Note: pip is unable to compile the dependencies when using a -run image.
# https://www.balena.io/docs/reference/base-images/base-images/#how-to-pick-a-base-image

# pip install python deps from requirements.txt
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY . /app
WORKDIR /app

CMD ["python", "mqtt-client.py"]