FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster-run

WORKDIR /usr/src/app

RUN install_packages wget nginx nginx-light

COPY static /var/www/html/static
COPY nginx.conf /etc/nginx/nginx.conf
COPY start.sh .

#CMD ["nginx", "-g", "daemon off;"]
CMD ["bash", "start.sh"]